version: "3.9"

services:
  mysql:
    image: mariadb:10.2
    volumes:
      - ./docker/mysql:/etc/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - taktik
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  taktik:
    driver: bridge
